apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-riak
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 3
  selector:
    name: riak
  template:
    metadata:
      labels:
        name: riak
    spec:
      containers:
        - name: riak
          image: quay.io/deisci/riak:v2-beta
          imagePullPolicy: Always
          env:
            - name:  RIAK_INET_DIST_MIN
              value: "6001"
            - name:  RIAK_INET_DIST_MAX
              value: "6001"
            - name: RIAK_JOIN_WAIT_TIME
              value: "5"
          ports:
            - containerPort: 4369
            - containerPort: 6001
            - containerPort: 8087
            - containerPort: 8098
            - containerPort: 8099
        - name: riak-cs
          image: quay.io/deisci/riak-cs:v2-beta
          imagePullPolicy: Always
          env:
            - name: LISTEN_HOST
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "8081"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: riak-cs-admin-user
              mountPath: /var/run/secrets/deis/riak-cs/admin-user
              readOnly: true
      volumes:
        - name: riak-cs-admin-user
          secret:
            secretName: riak-cs-admin-user
