apiVersion: v1
kind: Service
metadata:
  name: deis-riak-cluster
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - port: 8080
      targetPort: 8081
      name: http
      protocol: TCP
  selector:
    cluster_server: "true"
