apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-riak-cs
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 3
  selector:
    name: riak-cs
  template:
    metadata:
      labels:
        name: riak-cs
    spec:
      containers:
        - name: deis-riak-cs
          image: quay.io/deisci/riak-cs:v2-beta
          imagePullPolicy: Always
          env:
            - name: LISTEN_HOST
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "8081"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: riak-cs-admin-user
              mountPath: /var/run/secrets/deis/riak-cs/admin
              readOnly: true
      volumes:
        - name: riak-cs-admin-user
          secret:
            secretName: riak-cs-admin-user
